{
  "id": 22033837,
  "name": "save",
  "target": "branch",
  "source_type": "Repository",
  "source": "JulienVink/ZV",
  "enforcement": "disabled",
  "conditions": {
    "ref_name": {
      "exclude": [],
      "include": []
    }
  },
  "rules": [
    {
      "type": "deletion"
    },
    {
      "type": "non_fast_forward"
    }
  ],
  "bypass_actors": []
}
